### ISSUE TITLE
run error when using casanovo_massivekb_v3_0_0.ckpt

### ISSUE THREAD

**Issue by yanshu20220502** [Noble-Lab/casanovo#152]
```
2023-03-23 15:44:23,581 DEBUG [fsspec.local/MainProcess] local.__init__ : open file: C:/Users/Administrator/AppData/Local/casanovo/casanovo_massivekb_v3_0_0.ckpt
Traceback (most recent call last):
  File "E:\anaconda3\envs\casanovo_env\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\anaconda3\envs\casanovo_env\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\anaconda3\envs\casanovo_env\Scripts\casanovo.exe\__main__.py", line 7, in <module>
  File "E:\anaconda3\envs\casanovo_env\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "E:\anaconda3\envs\casanovo_env\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "E:\anaconda3\envs\casanovo_env\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "E:\anaconda3\envs\casanovo_env\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "E:\anaconda3\envs\casanovo_env\lib\site-packages\casanovo\casanovo.py", line 222, in main
    model_runner.predict(peak_path, model, config, writer)
  File "E:\anaconda3\envs\casanovo_env\lib\site-packages\casanovo\denovo\model_runner.py", line 46, in predict
    _execute_existing(peak_path, model_filename, config, False, out_writer)
  File "E:\anaconda3\envs\casanovo_env\lib\site-packages\casanovo\denovo\model_runner.py", line 99, in _execute_existing    model = Spec2Pep().load_from_checkpoint(
  File "E:\anaconda3\envs\casanovo_env\lib\site-packages\pytorch_lightning\core\saving.py", line 139, in load_from_checkpoint
    return _load_from_checkpoint(
  File "E:\anaconda3\envs\casanovo_env\lib\site-packages\pytorch_lightning\core\saving.py", line 160, in _load_from_checkpoint
    checkpoint = pl_load(checkpoint_path, map_location=map_location)
  File "E:\anaconda3\envs\casanovo_env\lib\site-packages\lightning_fabric\utilities\cloud_io.py", line 48, in _load
    return torch.load(f, map_location=map_location)
  File "E:\anaconda3\envs\casanovo_env\lib\site-packages\torch\serialization.py", line 777, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "E:\anaconda3\envs\casanovo_env\lib\site-packages\torch\serialization.py", line 282, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
```

**Comment by bittremieux** [comment]
Can you include the full log please? Did you download `casanovo_massivekb_v3_0_0.ckpt` manually or let Casanovo do this automatically?

In any case, I think the `casanovo_massivekb_v3_0_0.ckpt` file has gotten corrupted, potentially due to an interrupted download. Can you remove the file `C:/Users/Administrator/AppData/Local/casanovo/casanovo_massivekb_v3_0_0.ckpt` and then try running Casanovo again?

**Comment by yanshu20220502** [comment]
It doesn't seem to be a model problem. I recreate a conda environment and in this environment run commands "conda install pytorch torchvision torchaudio cpuonly -c pytorch", and "pip install casanovo". 
When I run "casanovo --help", I get the following error message:

Traceback (most recent call last):

File "E:\anaconda3\envs\casanovo\lib\runpy.py", line 196, in _run_module_as_main

return _run_code(code, main_globals, None,

File "E:\anaconda3\envs\casanovo\lib\runpy.py", line 86, in _run_code

exec(code, run_globals)

File "E:\anaconda3\envs\casanovo\Scripts\casanovo.exe\__main__.py", line 4, in &lt; module&gt;

File "E:\anaconda3\envs\casanovo\lib\site-packages\casanovo\casanovo.py", line 21, in &lt; module&gt;

from pytorch_lightning.lite import LightningLite

ModuleNotFoundError: No module named 'pytorch_lightning.lite'

**Comment by yanshu20220502** [comment]
It doesn't seem to be a model problem. I recreate a conda environment and in this environment run commands "conda install pytorch torchvision torchaudio cpuonly -c pytorch", and "pip install casanovo". 
When I run "casanovo --help", I get the following error message:

Traceback (most recent call last):

File "E:\anaconda3\envs\casanovo\lib\runpy.py", line 196, in _run_module_as_main

return _run_code(code, main_globals, None,

File "E:\anaconda3\envs\casanovo\lib\runpy.py", line 86, in _run_code

exec(code, run_globals)

File "E:\anaconda3\envs\casanovo\Scripts\casanovo.exe\__main__.py", line 4, in &lt; module&gt;

File "E:\anaconda3\envs\casanovo\lib\site-packages\casanovo\casanovo.py", line 21, in &lt; module&gt;

from pytorch_lightning.lite import LightningLite

ModuleNotFoundError: No module named 'pytorch_lightning.lite'

**Comment by yanshu20220502** [comment]
I have found the solution according to the issue published before, using "pip install pytorch_lightning==1.7". 
Thank you very much.
