### ISSUE TITLE
KeyError: 'A+42.011'

### ISSUE THREAD

**Issue by cguetot** [Noble-Lab/casanovo#158]
Hi there, 

I was testing casanovo on one mgf file and I got these error message:

"""
Traceback (most recent call last):
  File "/home/cguetot/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/cguetot/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 921, in _predict_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/cguetot/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1098, in _run
    results = self._run_stage()
  File "/home/cguetot/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1176, in _run_stage
    return self._run_predict()
  File "/home/cguetot/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1230, in _run_predict
    return self.predict_loop.run()
  File "/home/cguetot/.local/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 206, in run
    output = self.on_run_end()
  File "/home/cguetot/.local/lib/python3.10/site-packages/pytorch_lightning/loops/dataloader/prediction_loop.py", line 108, in on_run_end
    results = self._on_predict_epoch_end()
  File "/home/cguetot/.local/lib/python3.10/site-packages/pytorch_lightning/loops/dataloader/prediction_loop.py", line 132, in _on_predict_epoch_end
    self.trainer._call_lightning_module_hook("on_predict_epoch_end", results)
  File "/home/cguetot/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1342, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/srv/data1/home/cguetot/tools/miniconda3/envs/deepsearch/lib/python3.10/site-packages/casanovo/denovo/model.py", line 885, in on_predict_epoch_end
    self.peptide_mass_calculator.mass(peptide, charge),
  File "/srv/data1/home/cguetot/tools/miniconda3/envs/deepsearch/lib/python3.10/site-packages/depthcharge/masses.py", line 95, in mass
    calc_mass = sum([self.masses[aa] for aa in seq]) + self.h2o
  File "/srv/data1/home/cguetot/tools/miniconda3/envs/deepsearch/lib/python3.10/site-packages/depthcharge/masses.py", line 95, in <listcomp>
    calc_mass = sum([self.masses[aa] for aa in seq]) + self.h2o
KeyError: 'D+42.011'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/data1/home/cguetot/tools/miniconda3/envs/deepsearch/bin/casanovo", line 8, in <module>
    sys.exit(main())
  File "/srv/data1/home/cguetot/tools/miniconda3/envs/deepsearch/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/srv/data1/home/cguetot/tools/miniconda3/envs/deepsearch/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/srv/data1/home/cguetot/tools/miniconda3/envs/deepsearch/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/srv/data1/home/cguetot/tools/miniconda3/envs/deepsearch/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/srv/data1/home/cguetot/tools/miniconda3/envs/deepsearch/lib/python3.10/site-packages/casanovo/casanovo.py", line 165, in main
    model_runner.predict(peak_path, model, config, writer)
  File "/srv/data1/home/cguetot/tools/miniconda3/envs/deepsearch/lib/python3.10/site-packages/casanovo/denovo/model_runner.py", line 46, in predict
    _execute_existing(peak_path, model_filename, config, False, out_writer)
  File "/srv/data1/home/cguetot/tools/miniconda3/envs/deepsearch/lib/python3.10/site-packages/casanovo/denovo/model_runner.py", line 170, in _execute_existing
    run_trainer(model, loaders.test_dataloader())
  File "/home/cguetot/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 874, in predict
    return call._call_and_handle_interrupt(
  File "/home/cguetot/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 59, in _call_and_handle_interrupt
    trainer.strategy.reconciliate_processes(traceback.format_exc())
  File "/home/cguetot/.local/lib/python3.10/site-packages/pytorch_lightning/strategies/ddp.py", line 459, in reconciliate_processes
    os.kill(pid, signal.SIGKILL)
ProcessLookupError: [Errno 3] No such process
Traceback (most recent call last):
  File "/home/cguetot/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/cguetot/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 921, in _predict_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/cguetot/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1098, in _run
    results = self._run_stage()
  File "/home/cguetot/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1176, in _run_stage
    return self._run_predict()
  File "/home/cguetot/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1230, in _run_predict
    return self.predict_loop.run()
  File "/home/cguetot/.local/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 206, in run
    output = self.on_run_end()
  File "/home/cguetot/.local/lib/python3.10/site-packages/pytorch_lightning/loops/dataloader/prediction_loop.py", line 108, in on_run_end
    results = self._on_predict_epoch_end()
  File "/home/cguetot/.local/lib/python3.10/site-packages/pytorch_lightning/loops/dataloader/prediction_loop.py", line 132, in _on_predict_epoch_end
    self.trainer._call_lightning_module_hook("on_predict_epoch_end", results)
  File "/home/cguetot/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1342, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/srv/data1/home/cguetot/tools/miniconda3/envs/deepsearch/lib/python3.10/site-packages/casanovo/denovo/model.py", line 885, in on_predict_epoch_end
    self.peptide_mass_calculator.mass(peptide, charge),
  File "/srv/data1/home/cguetot/tools/miniconda3/envs/deepsearch/lib/python3.10/site-packages/depthcharge/masses.py", line 95, in mass
    calc_mass = sum([self.masses[aa] for aa in seq]) + self.h2o
  File "/srv/data1/home/cguetot/tools/miniconda3/envs/deepsearch/lib/python3.10/site-packages/depthcharge/masses.py", line 95, in <listcomp>
    calc_mass = sum([self.masses[aa] for aa in seq]) + self.h2o
KeyError: 'A+42.011'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/data1/home/cguetot/tools/miniconda3/envs/deepsearch/bin/casanovo", line 8, in <module>
    sys.exit(main())
  File "/srv/data1/home/cguetot/tools/miniconda3/envs/deepsearch/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/srv/data1/home/cguetot/tools/miniconda3/envs/deepsearch/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/srv/data1/home/cguetot/tools/miniconda3/envs/deepsearch/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/srv/data1/home/cguetot/tools/miniconda3/envs/deepsearch/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/srv/data1/home/cguetot/tools/miniconda3/envs/deepsearch/lib/python3.10/site-packages/casanovo/casanovo.py", line 165, in main
    model_runner.predict(peak_path, model, config, writer)
  File "/srv/data1/home/cguetot/tools/miniconda3/envs/deepsearch/lib/python3.10/site-packages/casanovo/denovo/model_runner.py", line 46, in predict
    _execute_existing(peak_path, model_filename, config, False, out_writer)
  File "/srv/data1/home/cguetot/tools/miniconda3/envs/deepsearch/lib/python3.10/site-packages/casanovo/denovo/model_runner.py", line 170, in _execute_existing
    run_trainer(model, loaders.test_dataloader())
  File "/home/cguetot/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 874, in predict
    return call._call_and_handle_interrupt(
  File "/home/cguetot/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 59, in _call_and_handle_interrupt
    trainer.strategy.reconciliate_processes(traceback.format_exc())
  File "/home/cguetot/.local/lib/python3.10/site-packages/pytorch_lightning/strategies/ddp.py", line 459, in reconciliate_processes
    os.kill(pid, signal.SIGKILL)
ProcessLookupError: [Errno 3] No such process
"""

thanks,

Carlos

**Comment by melihyilmaz** [comment]
Hi Carlos,

We will fix the issue of internal N-terminal modifications predicted by Casanovo with the incoming PR #139 . In the meantime, you can comment out [this line](https://github.com/Noble-Lab/casanovo/blob/29cedae86f515c1f4b9c1b04b3f8f8c5ee890e21/casanovo/denovo/model.py#L845) and replace it with a fixed value (e.g. 1) as a temporary and simple fix to run the model.
