### ISSUE TITLE
Casanovo-3.3.0  validation_step is not updated

### ISSUE THREAD

**Issue by r00bit** [Noble-Lab/casanovo#190]
Hi,
The newest version of casanovo3.3.0, returns the following error at validation_step function:

```
 peptides_pred_raw, _ = self.forward(batch[0], batch[1])
  ValueError: too many values to unpack (expected 2)
Because the list(self._get_top_peptide(pred_cache)) returns a list of predictions containing peptides with the highest confidence score
Here is the trackback error:
Traceback (most recent call last):
  File "/home/local/miniconda3/envs/casanovo_env_3.3.0/bin/casanovo", line 5, in <module>
    from casanovo.casanovo import main
  File "/home/local/Documentscasanovo-3.3.0/casanovo/casanovo.py", line 297, in <module>
    main()
  File "/home/local/Documentscasanovo-3.3.0/casanovo/casanovo.py", line 189, in main
    model_runner.train(peak_path, peak_path_val, model, config)
  File "/home/local/Documentscasanovo-3.3.0/casanovo/denovo/model_runner.py", line 320, in train
    trainer.fit(
  File "/home/local/miniconda3/envs/casanovo_env_3.3.0/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/home/local/miniconda3/envs/casanovo_env_3.3.0/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/local/miniconda3/envs/casanovo_env_3.3.0/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/home/local/miniconda3/envs/casanovo_env_3.3.0/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in _run
    results = self._run_stage()
  File "/home/local/miniconda3/envs/casanovo_env_3.3.0/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1191, in _run_stage
    self._run_train()
  File "/home/local/miniconda3/envs/casanovo_env_3.3.0/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1214, in _run_train
    self.fit_loop.run()
  File "/home/local/miniconda3/envs/casanovo_env_3.3.0/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/local/miniconda3/envs/casanovo_env_3.3.0/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 267, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/home/local/miniconda3/envs/casanovo_env_3.3.0/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.on_advance_end()
  File "/home/local/miniconda3/envs/casanovo_env_3.3.0/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 250, in on_advance_end
    self._run_validation()
  File "/home/local/miniconda3/envs/casanovo_env_3.3.0/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 308, in _run_validation
    self.val_loop.run()
  File "/home/local/miniconda3/envs/casanovo_env_3.3.0/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/local/miniconda3/envs/casanovo_env_3.3.0/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 152, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/local/miniconda3/envs/casanovo_env_3.3.0/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/local/miniconda3/envs/casanovo_env_3.3.0/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 137, in advance
    output = self._evaluation_step(**kwargs)
  File "/home/local/miniconda3/envs/casanovo_env_3.3.0/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 234, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/home/local/miniconda3/envs/casanovo_env_3.3.0/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1494, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/local/miniconda3/envs/casanovo_env_3.3.0/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 390, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/home/local/Documentscasanovo-3.3.0/casanovo/denovo/model.py", line 757, in validation_step
    peptides_pred_raw, _ = self.forward(batch[0], batch[1])
ValueError: too many values to unpack (expected 2)
Epoch 0:  50%|█████     | 2/4 [00:19<00:19,  9.73s/it, loss=3.47]  
```

Could you please let me know how I can fix it?
Thanks!

**Comment by bittremieux** [comment]
This was indeed a bug, which has recently been fixed (#164). Stay tuned for an updated v3.4.0 very soon (#194).

**Comment by bittremieux** [comment]
During training we only record the amino acid and peptide precision at coverage=1, to just track single values. The curves were generated after training was completed using some similar plotting functionality to get the precision at all coverage values, but this code is not directly included in this repository.

Btw version 3.4.0 has now been released.

**Comment by r00bit** [comment]
So, the precision-coverage curves are generated for test set. I am wondering where I can record the precision of aa and pep values based on coverage range, for example recording 5 precision values of pep level within range of 5 coverage (1, 0.9, 07, 05, 03).   
Thanks for releasing new update!

**Comment by bittremieux** [comment]
The precision-coverage curves are indeed generated on the test set, rather than during training/validation.

Here is some partial code which should pretty much do what you want, starting from PSMs read from a Casanovo mzTab to a DataFrame:
```
import depthcharge
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import auc

from casanovo.denovo import evaluate


aa_matches_batch = evaluate.aa_match_batch(
    psm_sequences["sequence"],
    psm_sequences["sequence_pred"],
    depthcharge.masses.PeptideMass("massivekb").masses,
)
peptide_matches = np.asarray([aa_match[1] for aa_match in aa_matches_batch[0]])
precision = np.cumsum(peptide_matches) / np.arange(1, len(peptide_matches) + 1)
coverage = np.arange(1, len(peptide_matches) + 1) / len(peptide_matches)
threshold = np.argmax(psm_sequences["search_engine_score[1]"] < 0)

print(f"Peptide precision = {precision[threshold]:.3f}")
print(f"Coverage = {coverage[threshold]:.3f}")
print(f"Peptide precision @ coverage=1 = {precision[-1]:.3f}")

width = 4
height = width / 1.618
fig, ax = plt.subplots(figsize=(width, width))

ax.plot(coverage, precision, label=f"Casanovo AUC = {auc(coverage, precision):.3f}")
ax.scatter(coverage[threshold], precision[threshold], s=50, marker="D", edgecolors="black", zorder=10)
ax.set_xlim(0, 1)
ax.set_ylim(0, 1)

ax.set_xlabel("Coverage")
ax.set_ylabel("Peptide precision")
ax.legend(loc="lower left")

plt.savefig("prec_cov.png", dpi=300, bbox_inches="tight")
plt.show()
plt.close()
```

(This is from an older version of the code, so maybe you'll have to do a few small updates.)

**Comment by r00bit** [comment]
Hello, 

I tried to replicate the precision-coverage curve for mouse data set reported on your paper.  
So, I splitted mouse data set into train, valid and test with 95, 5, 5 percentages respectively. I also added the out_writer in the validation_step to record the required information including   psm_sequences["sequence"], psm_sequences["sequence_pred"], search_engine_score[1]. Because the denovo algorithm in the on_predict_epoch_end doesn't record the true peptide sequence. 
I used your code:
`fname = 'mouse-casanovo-3.4.csv' #'casanovo_20230625164552.csv'
psm_pred_seq, psm_true_seq, thresholds = read_csv_by_col_name(fname)
aa_matches_batch, n_aa1, n_aa2 = aa_match_batch(psm_true_seq, psm_pred_seq, masses_dict)
peptide_matches = np.asarray([aa_match[1] for aa_match in aa_matches_batch])
precision_casanovo = np.cumsum(peptide_matches) / np.arange(1, len(peptide_matches) + 1)
coverage_casanovo = np.arange(1, len(peptide_matches) + 1) / len(peptide_matches)
thresholds = [float(i) for i in thresholds]
thresholds = np.array(thresholds)
threshold = np.argmax(thresholds[np.where(thresholds<0)])
width = 4
height = width / 1.618
fig, ax = plt.subplots(figsize=(width, width))

ax.plot(coverage_casanovo, precision_casanovo, 'g', label=f"Casanovo AUC = {auc(coverage_casanovo, precision_casanovo):.3f}")
ax.scatter(coverage_casanovo[threshold], precision_casanovo[threshold], s=5, marker="D", edgecolors="black", zorder=5)
ax.set_xlim(0, 1)
ax.set_ylim(0, 1)

ax.set_xlabel("Coverage")
ax.set_ylabel("Peptide precision")
ax.legend(loc="lower left")

plt.savefig("prec_cov_casanovo_mouse.png", dpi=300, bbox_inches="tight")
plt.show()`

However, I couldn't generate the same plot you reported on your paper that precision smoothly decrease by increasing the coverage. 
Would you please look at the files attached including the generated plot and csv file?
Thanks!
[mouse-casanovo-3.4.csv](https://github.com/Noble-Lab/casanovo/files/11961211/mouse-casanovo-3.4.csv)
![prec_cov_casanovo_mouse](https://github.com/Noble-Lab/casanovo/assets/44100934/5f7624c7-9aaf-45b7-8259-4fce8438a066)

**Comment by bittremieux** [comment]
Generally we evaluate a Casanovo after it has been fully trained by running inference as a post-processing step, rather than doing it directly during training.

A missing step in your code is that the predictions first need to be first ordered by descending score.

**Comment by bittremieux** [comment]
This is the updated code:
```
import depthcharge
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.metrics import auc

from casanovo.denovo import evaluate


psm_sequences = pd.read_csv("mouse-casanovo-3.4.csv", sep="\t", usecols=["sequence", "PSM_ID", "search_engine_score[1]"])
psm_sequences = psm_sequences.rename(columns={"PSM_ID": "sequence_pred"})

# This was the missing line.
psm_sequences = psm_sequences.sort_values("search_engine_score[1]", ascending=False)

aa_matches_batch = evaluate.aa_match_batch(
    psm_sequences["sequence"],
    psm_sequences["sequence_pred"],
    depthcharge.masses.PeptideMass("massivekb").masses,
)
peptide_matches = np.asarray([aa_match[1] for aa_match in aa_matches_batch[0]])
precision = np.cumsum(peptide_matches) / np.arange(1, len(peptide_matches) + 1)
coverage = np.arange(1, len(peptide_matches) + 1) / len(peptide_matches)
threshold = np.argmax(psm_sequences["search_engine_score[1]"] < 0)

print(f"Peptide precision = {precision[threshold]:.3f}")
print(f"Coverage = {coverage[threshold]:.3f}")
print(f"Peptide precision @ coverage=1 = {precision[-1]:.3f}")

width = 4
height = width / 1.618
fig, ax = plt.subplots(figsize=(width, width))

ax.plot(coverage, precision, label=f"Casanovo AUC = {auc(coverage, precision):.3f}")
ax.scatter(coverage[threshold], precision[threshold], s=50, marker="D", edgecolors="black", zorder=10)
ax.set_xlim(0, 1)
ax.set_ylim(0, 1)

ax.set_xlabel("Coverage")
ax.set_ylabel("Peptide precision")
ax.legend(loc="lower left")

plt.savefig("prec_cov.png", dpi=300, bbox_inches="tight")
plt.show()
plt.close()
```

And the corresponding output:
```
Peptide precision = 0.908
Coverage = 0.599
Peptide precision @ coverage=1 = 0.544
```
![prec_cov](https://github.com/Noble-Lab/casanovo/assets/10773123/8572ac12-f756-4c50-a4aa-0fbea93f16ad)

**Comment by r00bit** [comment]
Great, thank you so much for fixing it for me.
