### ISSUE TITLE
Error message from unlabeled training data

### ISSUE THREAD

**Issue by wsnoble** [Noble-Lab/casanovo#202]
I erroneously gave Casanovo a training file with no sequences in it, and it gave an inscrutable error message.  It should terminate with a message that says "No sequence annotation found for spectrum 1 in tiny.mgf."

```
(casanovo)-bash-4.2$ casanovo --mode=train --peak_path=tiny.mgf --peak_path_val=tiny.mgf
Global seed set to 454
2023-06-30 11:09:34,602 INFO [casanovo/MainProcess] casanovo.main : Casanovo version 3.4.0
2023-06-30 11:09:34,603 DEBUG [casanovo/MainProcess] casanovo.main : mode = train
2023-06-30 11:09:34,603 DEBUG [casanovo/MainProcess] casanovo.main : model = None
2023-06-30 11:09:34,603 DEBUG [casanovo/MainProcess] casanovo.main : peak_path = tiny.mgf
2023-06-30 11:09:34,603 DEBUG [casanovo/MainProcess] casanovo.main : peak_path_val = tiny.mgf
2023-06-30 11:09:34,603 DEBUG [casanovo/MainProcess] casanovo.main : config = default
2023-06-30 11:09:34,603 DEBUG [casanovo/MainProcess] casanovo.main : output = /net/noble/vol1/home/noble/proj/2023_wnoble_denovo-fdr/results/wnoble/2023-06-29train/casanovo_20230630110934
2023-06-30 11:09:34,603 DEBUG [casanovo/MainProcess] casanovo.main : random_seed = 454
2023-06-30 11:09:34,603 DEBUG [casanovo/MainProcess] casanovo.main : n_peaks = 150
2023-06-30 11:09:34,604 DEBUG [casanovo/MainProcess] casanovo.main : min_mz = 50.0
2023-06-30 11:09:34,604 DEBUG [casanovo/MainProcess] casanovo.main : max_mz = 2500.0
2023-06-30 11:09:34,604 DEBUG [casanovo/MainProcess] casanovo.main : min_intensity = 0.01
2023-06-30 11:09:34,604 DEBUG [casanovo/MainProcess] casanovo.main : remove_precursor_tol = 2.0
2023-06-30 11:09:34,604 DEBUG [casanovo/MainProcess] casanovo.main : max_charge = 10
2023-06-30 11:09:34,604 DEBUG [casanovo/MainProcess] casanovo.main : precursor_mass_tol = 50.0
2023-06-30 11:09:34,604 DEBUG [casanovo/MainProcess] casanovo.main : isotope_error_range = (0, 1)
2023-06-30 11:09:34,604 DEBUG [casanovo/MainProcess] casanovo.main : min_peptide_len = 6
2023-06-30 11:09:34,604 DEBUG [casanovo/MainProcess] casanovo.main : dim_model = 512
2023-06-30 11:09:34,604 DEBUG [casanovo/MainProcess] casanovo.main : n_head = 8
2023-06-30 11:09:34,604 DEBUG [casanovo/MainProcess] casanovo.main : dim_feedforward = 1024
2023-06-30 11:09:34,604 DEBUG [casanovo/MainProcess] casanovo.main : n_layers = 9
2023-06-30 11:09:34,604 DEBUG [casanovo/MainProcess] casanovo.main : dropout = 0.0
2023-06-30 11:09:34,604 DEBUG [casanovo/MainProcess] casanovo.main : dim_intensity = None
2023-06-30 11:09:34,604 DEBUG [casanovo/MainProcess] casanovo.main : custom_encoder = None
2023-06-30 11:09:34,604 DEBUG [casanovo/MainProcess] casanovo.main : max_length = 100
2023-06-30 11:09:34,605 DEBUG [casanovo/MainProcess] casanovo.main : residues = {'G': 57.021464, 'A': 71.037114, 'S': 87.032028, 'P': 97.052764, 'V': 99.068414, 'T': 101.04767, 'C+57.021': 160.030649, 'L': 113.084064, 'I': 113.084064, 'N': 114.042927, 'D': 115.026943, 'Q': 128.058578, 'K': 128.094963, 'E': 129.042593, 'M': 131.040485, 'H': 137.058912, 'F': 147.068414, 'R': 156.101111, 'Y': 163.063329, 'W': 186.079313, 'M+15.995': 147.0354, 'N+0.984': 115.026943, 'Q+0.984': 129.042594, '+42.011': 42.010565, '+43.006': 43.005814, '-17.027': -17.026549, '+43.006-17.027': 25.980265}
2023-06-30 11:09:34,605 DEBUG [casanovo/MainProcess] casanovo.main : n_log = 1
2023-06-30 11:09:34,605 DEBUG [casanovo/MainProcess] casanovo.main : tb_summarywriter = None
2023-06-30 11:09:34,605 DEBUG [casanovo/MainProcess] casanovo.main : warmup_iters = 100000
2023-06-30 11:09:34,605 DEBUG [casanovo/MainProcess] casanovo.main : max_iters = 600000
2023-06-30 11:09:34,605 DEBUG [casanovo/MainProcess] casanovo.main : learning_rate = 0.0005
2023-06-30 11:09:34,605 DEBUG [casanovo/MainProcess] casanovo.main : weight_decay = 1e-05
2023-06-30 11:09:34,605 DEBUG [casanovo/MainProcess] casanovo.main : train_batch_size = 32
2023-06-30 11:09:34,605 DEBUG [casanovo/MainProcess] casanovo.main : predict_batch_size = 1024
2023-06-30 11:09:34,605 DEBUG [casanovo/MainProcess] casanovo.main : n_beams = 5
2023-06-30 11:09:34,605 DEBUG [casanovo/MainProcess] casanovo.main : top_match = 1
2023-06-30 11:09:34,605 DEBUG [casanovo/MainProcess] casanovo.main : logger = None
2023-06-30 11:09:34,605 DEBUG [casanovo/MainProcess] casanovo.main : max_epochs = 30
2023-06-30 11:09:34,605 DEBUG [casanovo/MainProcess] casanovo.main : num_sanity_val_steps = 0
2023-06-30 11:09:34,605 DEBUG [casanovo/MainProcess] casanovo.main : train_from_scratch = True
2023-06-30 11:09:34,605 DEBUG [casanovo/MainProcess] casanovo.main : save_model = True
2023-06-30 11:09:34,606 DEBUG [casanovo/MainProcess] casanovo.main : model_save_folder_path = 
2023-06-30 11:09:34,606 DEBUG [casanovo/MainProcess] casanovo.main : save_weights_only = True
2023-06-30 11:09:34,606 DEBUG [casanovo/MainProcess] casanovo.main : every_n_train_steps = 50000
2023-06-30 11:09:34,606 DEBUG [casanovo/MainProcess] casanovo.main : no_gpu = False
2023-06-30 11:09:34,606 DEBUG [casanovo/MainProcess] casanovo.main : n_workers = 36
2023-06-30 11:09:34,606 INFO [casanovo/MainProcess] casanovo.main : Train the Casanovo model.
2023-06-30 11:09:34,609 INFO [depthcharge.data.hdf5/MainProcess] hdf5.__init__ : Reading 1 files...
/net/noble/vol1/home/noble/proj/2023_wnoble_denovo-fdr/results/wnoble/2023-06-29train/tiny.mgf: 12spectra [00:00, 3091.43spectra/s]
Traceback (most recent call last):
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo/bin/casanovo", line 8, in <module>
    sys.exit(main())
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo/lib/python3.10/site-packages/casanovo/casanovo.py", line 173, in main
    model_runner.train(peak_path, peak_path_val, model, config)
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo/lib/python3.10/site-packages/casanovo/denovo/model_runner.py", line 229, in train
    train_index = AnnotatedSpectrumIndex(
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo/lib/python3.10/site-packages/depthcharge/data/hdf5.py", line 445, in __init__
    super().__init__(
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo/lib/python3.10/site-packages/depthcharge/data/hdf5.py", line 104, in __init__
    self.add_file(ms_file)
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo/lib/python3.10/site-packages/depthcharge/data/hdf5.py", line 230, in add_file
    group.create_dataset(
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo/lib/python3.10/site-packages/h5py/_hl/group.py", line 183, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo/lib/python3.10/site-packages/h5py/_hl/dataset.py", line 168, in make_new_dset
    dset_id.write(h5s.ALL, h5s.ALL, data)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 280, in h5py.h5d.DatasetID.write
  File "h5py/_proxy.pyx", line 145, in h5py._proxy.dset_rw
  File "h5py/_conv.pyx", line 444, in h5py._conv.str2vlen
  File "h5py/_conv.pyx", line 95, in h5py._conv.generic_converter
  File "h5py/_conv.pyx", line 249, in h5py._conv.conv_str2vlen
TypeError: Can't implicitly convert non-string objects to strings
(casanovo)-bash-4.2$ 
```

[tiny.mgf.txt](https://github.com/Noble-Lab/casanovo/files/11919479/tiny.mgf.txt)

**Comment by bittremieux** [comment]
This is the same issue as #207, we can track its resolution there.
