### ISSUE TITLE
Warn for annotated spectra with unknown sequence formatting

### ISSUE THREAD

**Issue by wsnoble** [Noble-Lab/casanovo#207]
Anyone got a guess as to what this error might mean?  I am training on an MGF containing 2,373,619 spectra with Casanovo v3.4.0. According to the stderr output, the training read in 2,373,619 spectra and then died with this traceback:

```
Traceback (most recent call last):
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo/bin/casanovo", line 8, in <module>
    sys.exit(main())
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo/lib/python3.10/site-packages/casanovo/casanovo.py", line 173, in main
    model_runner.train(peak_path, peak_path_val, model, config)
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo/lib/python3.10/site-packages/casanovo/denovo/model_runner.py", line 229, in train
    train_index = AnnotatedSpectrumIndex(
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo/lib/python3.10/site-packages/depthcharge/data/hdf5.py", line 445, in __init__
    super().__init__(
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo/lib/python3.10/site-packages/depthcharge/data/hdf5.py", line 104, in __init__
    self.add_file(ms_file)
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo/lib/python3.10/site-packages/depthcharge/data/hdf5.py", line 230, in add_file
    group.create_dataset(
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo/lib/python3.10/site-packages/h5py/_hl/group.py", line 183, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo/lib/python3.10/site-packages/h5py/_hl/dataset.py", line 168, in make_new_dset
    dset_id.write(h5s.ALL, h5s.ALL, data)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 280, in h5py.h5d.DatasetID.write
  File "h5py/_proxy.pyx", line 145, in h5py._proxy.dset_rw
  File "h5py/_conv.pyx", line 444, in h5py._conv.str2vlen
  File "h5py/_conv.pyx", line 95, in h5py._conv.generic_converter
  File "h5py/_conv.pyx", line 249, in h5py._conv.conv_str2vlen
TypeError: Can't implicitly convert non-string objects to strings
```

FWIW, the log file is attached.
[decoy.log](https://github.com/Noble-Lab/casanovo/files/12004518/decoy.log)

**Comment by bittremieux** [comment]
There's something weird with your peptide labels. Can you grep and share them?

**Comment by wsnoble** [comment]
You're right.  I made two mistakes: I left them as "PEPTIDE=" instead of "SEQ=" and I forget to get rid of the enclosing square brackets.

It would be nice if the error message could be more informative.  I am guessing that it didn't even find the sequences at all, since they were labeled with "PEPTIDE=" instead of "SEQ=".

```
$ grep "PEPTIDE=" decoy.train.mgf | awk -F = '{print $2}' | head
VQEDDAPR
VAAAAEASADK
SSLANADSR
AQGTHEGCIEQTQR
LNLSHDAHDSQR
V[+43.0058]LSNLGQ[+0.9840]VVAHN[+0.9840]R
GVAM[+15.9949]NPVDHPHGGGEGR
THMQQVEASTGK
IATASQSDKPEAGAETK
V[+25.9803]IHAQGEQQ[+0.9840]AAEK
```

**Comment by Lilferrit** [comment]
It looks like this same (or a very similar) error is thrown when the ` AnnotatedSpectrumIndex` constructor is called with an unannotated MGF file in `ms_data_files`. Here's the output from that specific case:

```
casanovo\denovo\model_runner.py:183: in predict
    test_index = self._get_index(peak_path, evaluate, "")
casanovo\denovo\model_runner.py:420: in _get_index
    return Index(index_fname, filenames, valid_charge=valid_charge)
D:\anaconda3\envs\casanovo_env\lib\site-packages\depthcharge\data\hdf5.py:446: in __init__
    super().__init__(
D:\anaconda3\envs\casanovo_env\lib\site-packages\depthcharge\data\hdf5.py:104: in __init__
    self.add_file(ms_file)
D:\anaconda3\envs\casanovo_env\lib\site-packages\depthcharge\data\hdf5.py:231: in add_file
    group.create_dataset(
D:\anaconda3\envs\casanovo_env\lib\site-packages\h5py\_hl\group.py:183: in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
D:\anaconda3\envs\casanovo_env\lib\site-packages\h5py\_hl\dataset.py:166: in make_new_dset
    dset_id.write(h5s.ALL, h5s.ALL, data)
h5py\\_objects.pyx:54: in h5py._objects.with_phil.wrapper
    ???
h5py\\_objects.pyx:55: in h5py._objects.with_phil.wrapper
    ???
h5py\\h5d.pyx:282: in h5py.h5d.DatasetID.write
    ???
h5py\\_proxy.pyx:147: in h5py._proxy.dset_rw
    ???
h5py\\_conv.pyx:442: in h5py._conv.str2vlen
    ???
h5py\\_conv.pyx:96: in h5py._conv.generic_converter
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   TypeError: Can't implicitly convert non-string objects to strings

h5py\\_conv.pyx:247: TypeError
```

**Comment by bittremieux** [comment]
Fixed in #565.
