### ISSUE TITLE
TypeError: can't convert cuda:0 device type tensor to numpy

### ISSUE THREAD

**Issue by cfmelend** [Noble-Lab/casanovo#208]
Casanovo errors out in training mode at the end of an epoch w/a TypeError:

`TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.`

I've run into this error multiple times both w/a multi-enzyme dataset and a small (1000 sample; 80:20:20 train-val-test) subset of the original dataset used to train casanovo; it occurred this time after the 3rd epoch (it seems to occur somewhat randomly at the end of epochs). I'll attach my config file for this run as well.

Command:
casanovo --config=orig_test.yaml --mode=train --peak_path="$jobdir/custom_trainset.mgf" --peak_path_val="$jobdir/custom_valset.mgf" --output="results/${RUN_NAME}" 2> >(tee trouble_shooting/${RUN_NAME}_error.log)

torch version: 2.0.1+cu118

Cuda version: 12.1

Numpy version: 1.24.1

Casanovo version: 3.4.0

Error:
`2023-07-11 16:51:31,550 INFO [casanovo/MainProcess] model._log_history : 100	3.239988	nan	nan	nan`
```
Traceback (most recent call last):
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_testing/bin/casanovo", line 8, in <module>
    sys.exit(main())
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_testing/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_testing/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_testing/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_testing/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_testing/lib/python3.10/site-packages/casanovo/casanovo.py", line 173, in main
    model_runner.train(peak_path, peak_path_val, model, config)
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_testing/lib/python3.10/site-packages/casanovo/denovo/model_runner.py", line 318, in train
    trainer.fit(
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_testing/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_testing/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_testing/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_testing/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in _run
    results = self._run_stage()
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_testing/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1191, in _run_stage
    self._run_train()
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_testing/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1214, in _run_train
    self.fit_loop.run()
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_testing/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.on_advance_end()
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_testing/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 296, in on_advance_end
    self.trainer._call_lightning_module_hook("on_train_epoch_end")
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_testing/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1356, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_testing/lib/python3.10/site-packages/casanovo/denovo/model.py", line 833, in on_train_epoch_end
    self._log_history()
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_testing/lib/python3.10/site-packages/casanovo/denovo/model.py", line 916, in _log_history
    if not np.isnan(metric_value):
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_testing/lib/python3.10/site-packages/torch/_tensor.py", line 970, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
```

Update: Tried training the model on histidine w/CUDA 12.2 (same trainset+valset, same config) and ran into the same error. 

Update 2: I've replicated this with the vanilla torch install (CUDA 11.7 just installing torch without any other options) in a fresh conda environment. Same commands and same config setup+datasets. (I've added my environment.yml for more clarity about which packages are in the env)

[orig_test.txt](https://github.com/Noble-Lab/casanovo/files/12022382/orig_test.txt)
[casanovo_env_conda_yml.txt](https://github.com/Noble-Lab/casanovo/files/12032863/casanovo_env_conda_yml.txt)

**Comment by cfmelend** [comment]
Disabling the tb_summarywriter option in the config file (as noted [here](https://github.com/Noble-Lab/casanovo/issues/203)) stops this issue from occurring.
