### ISSUE TITLE
RuntimeError: No GPUs available.

### ISSUE THREAD

**Issue by hxxhust163** [Noble-Lab/casanovo#243]
hi

I tried the casanovo on my linux system. But failed. Could please help me? Thanks very much!

Best regard
Xiaoxiang

Following is the information of my GPU.
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.157                Driver Version: 390.157                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro P400         Off  | 00000000:73:00.0 Off |                  N/A |
| 34%   45C    P8    N/A /  N/A |     17MiB /  1998MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      2998      G   /usr/lib/xorg/Xorg                             9MiB |
|    0      3054      G   /usr/bin/gnome-shell                           4MiB |
+-----------------------------------------------------------------------------+
```

I got the error as follows:
```
Traceback (most recent call last):
  File "/home/xhuang/anaconda3/envs/casanovo_env/bin/casanovo", line 8, in <module>
    sys.exit(main())
  File "/home/xhuang/anaconda3/envs/casanovo_env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/xhuang/anaconda3/envs/casanovo_env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/xhuang/anaconda3/envs/casanovo_env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/xhuang/anaconda3/envs/casanovo_env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/xhuang/anaconda3/envs/casanovo_env/lib/python3.10/site-packages/casanovo/casanovo.py", line 166, in main
    model_runner.predict(peak_path, model, config, writer)
  File "/home/xhuang/anaconda3/envs/casanovo_env/lib/python3.10/site-packages/casanovo/denovo/model_runner.py", line 46, in predict
    _execute_existing(peak_path, model_filename, config, False, out_writer)
  File "/home/xhuang/anaconda3/envs/casanovo_env/lib/python3.10/site-packages/casanovo/denovo/model_runner.py", line 159, in _execute_existing
    trainer = pl.Trainer(
  File "/home/xhuang/anaconda3/envs/casanovo_env/lib/python3.10/site-packages/pytorch_lightning/utilities/argparse.py", line 348, in insert_env_defaults
    return fn(self, **kwargs)
  File "/home/xhuang/anaconda3/envs/casanovo_env/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 420, in __init__
    self._accelerator_connector = AcceleratorConnector(
  File "/home/xhuang/anaconda3/envs/casanovo_env/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 204, in __init__
    self._set_parallel_devices_and_init_accelerator()
  File "/home/xhuang/anaconda3/envs/casanovo_env/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 577, in _set_parallel_devices_and_init_accelerator
    self._set_devices_flag_if_auto_select_gpus_passed()
  File "/home/xhuang/anaconda3/envs/casanovo_env/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 594, in _set_devices_flag_if_auto_select_gpus_passed
    self._devices_flag = pick_multiple_gpus(
  File "/home/xhuang/anaconda3/envs/casanovo_env/lib/python3.10/site-packages/pytorch_lightning/tuner/auto_gpu_select.py", line 54, in pick_multiple_gpus
    picked.append(pick_single_gpu(exclude_gpus=picked, _show_deprecation=False))
  File "/home/xhuang/anaconda3/envs/casanovo_env/lib/python3.10/site-packages/pytorch_lightning/tuner/auto_gpu_select.py", line 96, in pick_single_gpu
    raise RuntimeError("No GPUs available.")
RuntimeError: No GPUs available.
```

**Comment by melihyilmaz** [comment]
Hi Xiaoxiang, can you try updating your local CUDA installation? You may not even have it installed because I can't see it on the header of GPU information you shared. You can see how it'd look like below:

+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2     |
|-------------------------------+----------------------+----------------------+
