### ISSUE TITLE
Add docs for reproduction of main model training

### ISSUE THREAD

**Issue by gdewael** [Noble-Lab/casanovo#283]
When going through the repository / docs, it is not clear how to reproduce a full model training run.
Currently, I am encountering errors with unknown amino acid keys (e.g. "N[0.98]" or "R."

Steps followed:
1. Casanovo installed in a conda env and ensured proper functioning with `casanovo --help`
2. Downloaded data from the nine species benchmark `ftp://massive.ucsd.edu/v01/MSV000090982` under `updates/2023-03-08_woutb_2c43c18c/peak`
3. Used some random files therein as training and validation `.mgf` files. e.g. `casanovo train --validation_peak_path Mus-musculus/20160323_CoAN_WT3_3377.mgf Mus-musculus/20160323_CoAN_WT2_3376.mgf`
The following crashes:
<details><summary>Traceback</summary>
<p>

```
Traceback (most recent call last):
  File "/opt/Anaconda3/envs/gaetan_msms/bin/casanovo", line 8, in <module>
    sys.exit(main())
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/rich_click/rich_command.py", line 126, in main
    rv = self.invoke(ctx)
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/data/home/gaetandw/msms/casanovo/casanovo/casanovo.py", line 220, in train
    runner.train(train_peak_path, validation_peak_path)
  File "/data/home/gaetandw/msms/casanovo/casanovo/denovo/model_runner.py", line 107, in train
    self.trainer.fit(
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/lightning/pytorch/strategies/launchers/subprocess_script.py", line 102, in launch
    return function(*args, **kwargs)
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 989, in _run
    results = self._run_stage()
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 1035, in _run_stage
    self.fit_loop.run()
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py", line 202, in run
    self.advance()
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py", line 359, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 136, in run
    self.advance(data_fetcher)
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 240, in advance
    batch_output = self.automatic_optimization.run(trainer.optimizers[0], batch_idx, kwargs)
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/lightning/pytorch/loops/optimization/automatic.py", line 187, in run
    self._optimizer_step(batch_idx, closure)
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/lightning/pytorch/loops/optimization/automatic.py", line 265, in _optimizer_step
    call._call_lightning_module_hook(
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 157, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/lightning/pytorch/core/module.py", line 1291, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/lightning/pytorch/core/optimizer.py", line 151, in step
    step_output = self._strategy.optimizer_step(self._optimizer, closure, **kwargs)
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/lightning/pytorch/strategies/ddp.py", line 265, in optimizer_step
    optimizer_output = super().optimizer_step(optimizer, closure, model, **kwargs)
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/lightning/pytorch/strategies/strategy.py", line 230, in optimizer_step
    return self.precision_plugin.optimizer_step(optimizer, model=model, closure=closure, **kwargs)
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/lightning/pytorch/plugins/precision/precision.py", line 117, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 68, in wrapper
    return wrapped(*args, **kwargs)
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/torch/optim/optimizer.py", line 373, in wrapper
    out = func(*args, **kwargs)
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/torch/optim/optimizer.py", line 76, in _use_grad
    ret = func(self, *args, **kwargs)
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/torch/optim/adam.py", line 143, in step
    loss = closure()
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/lightning/pytorch/plugins/precision/precision.py", line 104, in _wrap_closure
    closure_result = closure()
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/lightning/pytorch/loops/optimization/automatic.py", line 140, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/lightning/pytorch/loops/optimization/automatic.py", line 126, in closure
    step_output = self._step_fn()
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/lightning/pytorch/loops/optimization/automatic.py", line 315, in _training_step
    training_step_output = call._call_strategy_hook(trainer, "training_step", *kwargs.values())
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 309, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/lightning/pytorch/strategies/strategy.py", line 381, in training_step
    return self._forward_redirection(self.model, self.lightning_module, "training_step", *args, **kwargs)
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/lightning/pytorch/strategies/strategy.py", line 633, in __call__
    wrapper_output = wrapper_module(*args, **kwargs)
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1519, in forward
    else self._run_ddp_forward(*inputs, **kwargs)
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1355, in _run_ddp_forward
    return self.module(*inputs, **kwargs)  # type: ignore[index]
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/lightning/pytorch/strategies/strategy.py", line 626, in wrapped_forward
    out = method(*_args, **_kwargs)
  File "/data/home/gaetandw/msms/casanovo/casanovo/denovo/model.py", line 730, in training_step
    pred, truth = self._forward_step(*batch)
  File "/data/home/gaetandw/msms/casanovo/casanovo/denovo/model.py", line 706, in _forward_step
    return self.decoder(sequences, precursors, *self.encoder(spectra))
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/depthcharge/components/transformers.py", line 422, in forward
    tokens = [self.tokenize(s) for s in sequences]
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/depthcharge/components/transformers.py", line 422, in <listcomp>
    tokens = [self.tokenize(s) for s in sequences]
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/depthcharge/components/transformers.py", line 183, in tokenize
    tokens = [self._aa2idx[aa] for aa in sequence]
  File "/opt/Anaconda3/envs/gaetan_msms/lib/python3.10/site-packages/depthcharge/components/transformers.py", line 183, in <listcomp>
    tokens = [self._aa2idx[aa] for aa in sequence]
KeyError: 'R.'
```

</p>
</details> 

Using the sample data included in the repository works without errors.
I note that using the original mgf files (not the updated ones), also give similar errors.
I'm not too familiar with the field but I can only assume this is some sort of PTM?

More documentation on how to reproduce the main experiments of the paper w.r.t. model training would be useful!

Cheers, Gaetan

**Comment by bittremieux** [comment]
You're right, the annotated MGF files from both the original and revised nine-species benchmark data are not directly compatible with Casanovo due to the way PTMs are encoded in the peptide sequences. By default, Casanovo uses a MassIVE-KB style encoding, which has the modification mass, with three decimals, directly in the peptide sequence (e.g. `M+15.995YPEP`). In contrast, the original nine-species data uses parentheses and only two decimals (e.g. `M(+15.99)YPEP`), and the revised nine-species benchmark data uses the Tide syntax with square brackets, four decimals, and no explicit sign (e.g. `M[15.9949]YPEP`).

It's a mess, I know. 😳 Ultimately we want to standardize on the [ProForma syntax](https://github.com/HUPO-PSI/ProForma) for modified sequences (#201), but for now the workaround we've been using is to do a simple string convert between those encodings:

- For the original nine-species data:
```
mod_dict = {"(+57.02)": "+57.021", "(+15.99)": "+15.995", "(+.98)": "+0.984"}
```

- For the revised nine-species data:
```
mod_dict = {
    "C": "C+57.021",
    "M[15.9949]": "M+15.995",
    "[0.9840]": "+0.984",
}

n_term_mods = { 
    "[-17.0265]": "-17.027",
    "[42.0106]": "+42.011",
    "[43.0058]": "+43.006",
    "[25.9803]": "+43.006-17.027",
}
```

Maybe a brief consolation: data from [MassIVE-KB](https://massive.ucsd.edu/ProteoSAFe/static/massive-kb-libraries.jsp) should work directly.
