### ISSUE TITLE
Using HDF5 file as train/val dataset leads to index out of bound error 

### ISSUE THREAD

**Issue by cfmelend** [Noble-Lab/casanovo#311]
I'm attempting to train Casanovo using the latest `dev` branch with preprocessed hdf5 files generated by `depthcharge`, however when using these as inputs I appear to run into an indexing error during either training/validation when the dataloaders attempt to access the hdf5 to retrieve a new batch. This is similar to an error I've observed while manually creating depthcharge `SpectrumIndex` objects during my own experiments without removing a previously written hdf5 file (the same data appears to be written twice). I've attached the two hdf5 files along with the config file I'm using to this post.
[test_data.val.hdf5.txt](https://github.com/Noble-Lab/casanovo/files/14531661/test_data.val.hdf5.txt)
[test_data.train.hdf5.txt](https://github.com/Noble-Lab/casanovo/files/14531662/test_data.train.hdf5.txt)
[test.yaml.txt](https://github.com/Noble-Lab/casanovo/files/14531663/test.yaml.txt)

> Epoch 0:   3%|▎         | 1/32 [00:27<14:18,  0.04it/s, v_num=1]Traceback (most recent call last):
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_main/bin/casanovo", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_main/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_main/lib/python3.11/site-packages/rich_click/rich_command.py", line 126, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_main/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_main/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_main/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/net/noble/vol1/home/cfmelend/proj/casanovo/casanovo/casanovo.py", line 221, in train
    runner.train(train_peak_path, validation_peak_path)
  File "/net/noble/vol1/home/cfmelend/proj/casanovo/casanovo/denovo/model_runner.py", line 108, in train
    self.trainer.fit(
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_main/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 543, in fit
    call._call_and_handle_interrupt(
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_main/lib/python3.11/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_main/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 579, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_main/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 986, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_main/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 1032, in _run_stage
    self.fit_loop.run()
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_main/lib/python3.11/site-packages/lightning/pytorch/loops/fit_loop.py", line 205, in run
    self.advance()
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_main/lib/python3.11/site-packages/lightning/pytorch/loops/fit_loop.py", line 363, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_main/lib/python3.11/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 138, in run
    self.advance(data_fetcher)
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_main/lib/python3.11/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 204, in advance
    batch, _, __ = next(data_fetcher)
                   ^^^^^^^^^^^^^^^^^^
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_main/lib/python3.11/site-packages/lightning/pytorch/loops/fetchers.py", line 133, in __next__
    batch = super().__next__()
            ^^^^^^^^^^^^^^^^^^
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_main/lib/python3.11/site-packages/lightning/pytorch/loops/fetchers.py", line 60, in __next__
    batch = next(self.iterator)
            ^^^^^^^^^^^^^^^^^^^
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_main/lib/python3.11/site-packages/lightning/pytorch/utilities/combined_loader.py", line 341, in __next__
    out = next(self._iterator)
          ^^^^^^^^^^^^^^^^^^^^
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_main/lib/python3.11/site-packages/lightning/pytorch/utilities/combined_loader.py", line 78, in __next__
    out[i] = next(self.iterators[i])
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_main/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_main/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_main/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_main/lib/python3.11/site-packages/torch/_utils.py", line 722, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_main/lib/python3.11/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
           ^^^^^^^^^^^^^^^^^^^^
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_main/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_main/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/net/noble/vol1/home/cfmelend/proj/casanovo/casanovo/data/datasets.py", line 263, in __getitem__
    ) = self.index[idx]
        ~~~~~~~~~~^^^^^
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_main/lib/python3.11/site-packages/depthcharge/data/hdf5.py", line 335, in __getitem__
    return self.get_spectrum(idx)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_main/lib/python3.11/site-packages/depthcharge/data/hdf5.py", line 480, in get_spectrum
    spec_info = super().get_spectrum(idx)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/net/noble/vol1/home/cfmelend/miniconda3/envs/cas_main/lib/python3.11/site-packages/depthcharge/data/hdf5.py", line 272, in get_spectrum
    start_offset = offsets[0]
                   ~~~~~~~^^^
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by bittremieux** [comment]
I don't think that this is a Casanovo/DepthCharge bug, but rather that for some reason your HDF5 files are corrupted.

Until we add proper support for re-using spectrum indexes, rather than the hacky quickly copying it over, doing this is at the user's own risk.

**Comment by wsnoble** [comment]
@bittremieux any advice on how Carlo can check whether his hdf5 file is corrupted?

**Comment by tuanle618** [comment]
I also faced the issue when creating a new hdf5 index using depthcharge v0.2.3.
How can I fix this @bittremieux, @wsnoble  ?

**Comment by bittremieux** [comment]
Can you provide some more details, including your log file, system information, etc.

This bug occurred only when Casanovo was used in a non-standard way, so we need more details to understand what's happening.

**Comment by bittremieux** [comment]
How did you create those `trainpeaks.hdf5` and `valpeaks.hdf5` files? Because Casanovo doesn't export those for the users by default.

Additionally, the listed Casanovo version is `0.1.dev330+g42882f8.d20240522`, which is probably because you installed from the source rather than the official PyPI package. Please use the latest Casanovo version 4.2.0 instead to avoid issues due to an uncontrolled setup.

**Comment by tuanle618** [comment]
I've created the `trainpeaks.hdf5` and `valpeaks.hdf5`  files using the `AnnotatedSpectrumIndex` from `depthcharge.data` from version 0.2.3 - I think this should be fine since casanovo also creates the index that way? As `ms_data_files` I pass the path, where all the .mgf files are stored.

**Comment by bittremieux** [comment]
Unfortunately this non-standard use is very hard for us to debug. As Casanovo works correctly, we will not investigate this further. If you think that there is a specific bug with creating the index, you can open an issue on the DepthCharge repository. However, considering that we haven't encountered this issue with other usages of DepthCharge, in Casanovo and several other projects, I recommend that you first double-check your own code.

**Comment by tuanle618** [comment]
I understand. It's fine - I will try debug and see whether the error is when moving to the newest depthcharge version. I just thought it would make sense to save the .hdf5 once and re-use it again instead of processing it every time one wants to run a training.

Thank you!
