### ISSUE TITLE
Some questions when I tried to train a new casanovo model from scratch...

### ISSUE THREAD

**Issue by dadadalizi146** [Noble-Lab/casanovo#367]
Hello,
     When I tried to train a new casanovo model, I ran into the following problem:
     1. the train loss or validation loss is nan...
         So far, I've tried to train for two epochs, but the validation loss(train loss) of the first two epochs is nan frequently. Is this normal?
     2. OSError: [Errno 24] Too many open files.
        According to the follwing information, I think that this error occurs at the end of the first epoch and before the second epoch. I tried to solve this error by using command "ulimit -n 4096"(before is 1024) to enlarge the number of the files open at the same time, but it didn't work.  

Epoch 0: 100%|██████████| 33440/33440 [53:01<00:00, 10.51it/s, v_num=16670]INFO: 33440	nan	nan
Epoch 0:   0%|          | 0/33440 [00:00<?, ?it/s, v_num=16670]            
Epoch 1:   0%|          | 0/33440 [00:00<?, ?it/s, v_num=16670]
Traceback (most recent call last):
  File "/share/home/ppp/.local/bin/casanovo", line 8, in <module>
    sys.exit(main())
  File "/share/home/ppp/.local/lib/python3.9/site-packages/rich_click/rich_command.py", line 367, in __call__
    return super().__call__(*args, **kwargs)
  File "/share/home/ppp/.local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/share/home/ppp/.local/lib/python3.9/site-packages/rich_click/rich_command.py", line 152, in main
    rv = self.invoke(ctx)
  File "/share/home/ppp/.local/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/share/home/ppp/.local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/share/home/ppp/.local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/share/home/ppp/.local/lib/python3.9/site-packages/casanovo/casanovo.py", line 221, in train
    runner.train(train_peak_path, validation_peak_path)
  File "/share/home/ppp/.local/lib/python3.9/site-packages/casanovo/denovo/model_runner.py", line 108, in train
    self.trainer.fit(
  File "/share/home/ppp/.local/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 543, in fit
    call._call_and_handle_interrupt(
  File "/share/home/ppp/.local/lib/python3.9/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/share/home/ppp/.local/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 579, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/share/home/ppp/.local/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 986, in _run
    results = self._run_stage()
  File "/share/home/ppp/.local/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 1030, in _run_stage
    self.fit_loop.run()
  File "/share/home/ppp/.local/lib/python3.9/site-packages/lightning/pytorch/loops/fit_loop.py", line 205, in run
    self.advance()
  File "/share/home/ppp/.local/lib/python3.9/site-packages/lightning/pytorch/loops/fit_loop.py", line 363, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/share/home/ppp/.local/lib/python3.9/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 137, in run
    self.on_run_start(data_fetcher)
  File "/share/home/ppp/.local/lib/python3.9/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 179, in on_run_start
    iter(data_fetcher)  # creates the iterator inside the fetcher
  File "/share/home/ppp/.local/lib/python3.9/site-packages/lightning/pytorch/loops/fetchers.py", line 104, in __iter__
    super().__iter__()
  File "/share/home/ppp/.local/lib/python3.9/site-packages/lightning/pytorch/loops/fetchers.py", line 51, in __iter__
    self.iterator = iter(self.combined_loader)
  File "/share/home/ppp/.local/lib/python3.9/site-packages/lightning/pytorch/utilities/combined_loader.py", line 351, in __iter__
    iter(iterator)
  File "/share/home/ppp/.local/lib/python3.9/site-packages/lightning/pytorch/utilities/combined_loader.py", line 92, in __iter__
    super().__iter__()
  File "/share/home/ppp/.local/lib/python3.9/site-packages/lightning/pytorch/utilities/combined_loader.py", line 43, in __iter__
    self.iterators = [iter(iterable) for iterable in self.iterables]
  File "/share/home/ppp/.local/lib/python3.9/site-packages/lightning/pytorch/utilities/combined_loader.py", line 43, in <listcomp>
    self.iterators = [iter(iterable) for iterable in self.iterables]
  File "/share/home/ppp/.local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 439, in __iter__
    return self._get_iterator()
  File "/share/home/ppp/.local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 387, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/share/home/ppp/.local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1040, in __init__
    w.start()
  File "/share/apps/miniconda3_23/envs/pytorch/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/share/apps/miniconda3_23/envs/pytorch/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/share/apps/miniconda3_23/envs/pytorch/lib/python3.9/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/share/apps/miniconda3_23/envs/pytorch/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/share/apps/miniconda3_23/envs/pytorch/lib/python3.9/multiprocessing/popen_fork.py", line 64, in _launch
    parent_r, child_w = os.pipe()
OSError: [Errno 24] Too many open files

Epoch 1:   0%|          | 0/33440 [00:05<?, ?it/s, v_num=16670]

enviroment:
    GPU： A800
   version： casanovo 4.2.0
   system： linux

**Comment by dadadalizi146** [comment]
2024.08.19 
The second question has been solved by set a large ulimit....
As for the first question, I'm not sure if the loss recorded in the log file is normal. There are many nan values that appear blew :

2024-08-19 13:28:48,101 INFO [casanovo/MainProcess] model._log_history : Step	Train loss	Valid loss	
2024-08-19 13:28:48,101 INFO [casanovo/MainProcess] model._log_history : 20000	nan	1.594399
2024-08-19 13:49:20,856 INFO [casanovo/MainProcess] model._log_history : 33440	1.816622	nan
2024-08-19 14:01:56,689 INFO [casanovo/MainProcess] model._log_history : 40000	nan	1.010075
2024-08-19 14:34:15,835 INFO [casanovo/MainProcess] model._log_history : 60000	nan	0.746913
2024-08-19 14:44:42,826 INFO [casanovo/MainProcess] model._log_history : 66880	0.945725	nan
2024-08-19 15:07:10,980 INFO [casanovo/MainProcess] model._log_history : 80000	nan	0.643513
2024-08-19 15:39:42,118 INFO [casanovo/MainProcess] model._log_history : 100000	nan	0.582115
2024-08-19 15:40:13,280 INFO [casanovo/MainProcess] model._log_history : 100320	0.712074	nan
2024-08-19 16:14:05,699 INFO [casanovo/MainProcess] model._log_history : 120000	nan	0.512935
2024-08-19 16:36:41,683 INFO [casanovo/MainProcess] model._log_history : 133760	0.596518	nan
2024-08-19 16:51:00,203 INFO [casanovo/MainProcess] model._log_history : 140000	nan	0.459005
2024-08-19 17:28:04,681 INFO [casanovo/MainProcess] model._log_history : 160000	nan	0.421830
2024-08-19 17:40:40,756 INFO [casanovo/MainProcess] model._log_history : 167200	0.506324	nan
2024-08-19 18:07:39,867 INFO [casanovo/MainProcess] model._log_history : 180000	nan	0.394685

And I noticed that:
   The size of the training dataset is 34400 steps, and the model calculates the loss of the validation set every 20,000 steps. So the model will caiculate the loss of the validation set twice in each epoch. Once at 20,000 steps and the other at the end of the entire epoch. We can notice that the train loss will be nan for the former and the valid loss will be nan for the latter...    Is this normal???

**Comment by rxnataliezhang** [comment]
I think this is normal as it extracts loss for train and validation for different steps. However, when I continue my training, I met a problem that loss for both train and eval is nan until all epochs(50 at default) is done. 
<img width="1008" alt="Screenshot 2024-08-19 at 09 27 35" src="https://github.com/user-attachments/assets/2ead6132-c16b-4d39-810e-4d2306d843cf">

**Comment by bittremieux** [comment]
The train and validation loss in turns being `nan` is expected behavior. This is because both losses are computed at different times:
1. The training loss is recorded at the end of each training epoch. The validation loss is not recorded at that point and will be reported as `nan`.
2. The validation loss is recorded every [`val_check_interval`](https://github.com/Noble-Lab/casanovo/blob/main/casanovo/config.yaml#L51) steps, which is 50,000 by default (rather than 20,000, so I assumed you changed this in the config). This only records the validation loss, so the training loss is reported as `nan`.

This can indeed be a bit confusing and we want to make this more clear (#204), but it's not a bug.

I have never seen the error concerning too many open files. Can you provide some more information on which dataset you're training Casanovo and attach the full log file?

**Comment by bittremieux** [comment]
@rxnataliezhang We never actually train for the full 50 epochs, that default value is mostly just a placeholder. I suspect that due to the long training you're running into exploding or vanishing gradients, which then also results in a `nan` loss.

Additionally, your training and validation loss seem to have diverged, so the extra training is not resulting in any more benefits.

**Comment by rxnataliezhang** [comment]
> @rxnataliezhang We never actually train for the full 50 epochs, that default value is mostly just a placeholder. I suspect that due to the long training you're running into exploding or vanishing gradients, which then also results in a `nan` loss.
> 
> Additionally, your training and validation loss seem to have diverged, so the extra training is not resulting in any more benefits.

I think the training loss doesn't diverge and the validation loss is vibrating. I also tried with larger batch size and same thing happened. Then I used the last ckpt to continue training, and it got overfitting.

I will try with smaller lr afterwards and let you know what happens.

<img width="915" alt="Screenshot 2024-08-21 at 12 40 05" src="https://github.com/user-attachments/assets/f5a25443-072f-491e-9750-000adf9efea0">
<img width="868" alt="Screenshot 2024-08-21 at 12 46 22" src="https://github.com/user-attachments/assets/ab80e618-f8e5-4a13-9c82-ba3dc685c631">

**Comment by bittremieux** [comment]
> I think the training loss doesn't diverge and the validation loss is vibrating. I also tried with larger batch size and same thing happened. Then I used the last ckpt to continue training, and it got overfitting.

Training loss is always expected to go down, that's normal for almost all neural network applications. However, you see here a pretty large gap between training and validation loss. This indicates that you're either overfitting or that the validation data is not i.i.d. In our Casanovo training runs, training and validation loss are always highly similar to each other.

**Comment by bittremieux** [comment]
> I also tried with larger batch size and same thing happened. Then I used the last ckpt to continue training, and it got overfitting.
> 
> I will try with smaller lr afterwards and let you know what happens.

This is a strong indication where to look for the issue. Modifying the batch size and/or the learning rate can make learning unstable, so you need to be careful in tuning those values.

Considering that the initial questions have been resolved, I'll close this issue. If you suspect that something weird is going on, feel free to reopen it or make a new one.
