### ISSUE TITLE
 WARNING: Skipped 56750 spectra with invalid precursor info - results in error

### ISSUE THREAD

**Issue by mriffle** [Noble-Lab/casanovo#383]
## Describe the Issue
I am running casanovo with this command:

```
casanovo sequence         --config casanovo.yaml         --model casanovo_v4_2_0.ckpt         --output results.mztab         D_2023_0725_RJ_28_k562.mzML         > >(tee "D_2023_0725_RJ_28_k562.casanovo.stdout") 2> >(tee "D_2023_0725_RJ_28_k562.casanovo.stderr" >&2)
```

I get this output and error:

```
...
  D_2023_0725_RJ_28_k562.mzML:  91%|█████████ | 53154/58318 [00:21<00:02, 2421.60spectra/s]
  D_2023_0725_RJ_28_k562.mzML:  92%|█████████▏| 53410/58318 [00:21<00:01, 2461.28spectra/s]
  D_2023_0725_RJ_28_k562.mzML:  92%|█████████▏| 53662/58318 [00:21<00:01, 2475.93spectra/s]
  D_2023_0725_RJ_28_k562.mzML:  92%|█████████▏| 53910/58318 [00:21<00:01, 2453.47spectra/s]
  D_2023_0725_RJ_28_k562.mzML:  93%|█████████▎| 54159/58318 [00:21<00:01, 2464.04spectra/s]
  D_2023_0725_RJ_28_k562.mzML:  93%|█████████▎| 54409/58318 [00:21<00:01, 2473.25spectra/s]
  D_2023_0725_RJ_28_k562.mzML:  94%|█████████▎| 54657/58318 [00:22<00:01, 2453.35spectra/s]
  D_2023_0725_RJ_28_k562.mzML:  94%|█████████▍| 54903/58318 [00:22<00:01, 2423.81spectra/s]
  D_2023_0725_RJ_28_k562.mzML:  95%|█████████▍| 55146/58318 [00:22<00:01, 2407.16spectra/s]
  D_2023_0725_RJ_28_k562.mzML:  95%|█████████▍| 55389/58318 [00:22<00:01, 2413.19spectra/s]
  D_2023_0725_RJ_28_k562.mzML:  95%|█████████▌| 55661/58318 [00:22<00:01, 2502.99spectra/s]
  D_2023_0725_RJ_28_k562.mzML:  96%|█████████▌| 55929/58318 [00:22<00:00, 2555.47spectra/s]
  D_2023_0725_RJ_28_k562.mzML:  96%|█████████▋| 56185/58318 [00:22<00:00, 2466.35spectra/s]
  D_2023_0725_RJ_28_k562.mzML:  97%|█████████▋| 56456/58318 [00:22<00:00, 2535.29spectra/s]
  D_2023_0725_RJ_28_k562.mzML:  97%|█████████▋| 56730/58318 [00:22<00:00, 2595.37spectra/s]
  D_2023_0725_RJ_28_k562.mzML:  98%|█████████▊| 57010/58318 [00:22<00:00, 2655.67spectra/s]
  D_2023_0725_RJ_28_k562.mzML:  98%|█████████▊| 57301/58318 [00:23<00:00, 2729.39spectra/s]
  D_2023_0725_RJ_28_k562.mzML:  99%|█████████▊| 57585/58318 [00:23<00:00, 2755.81spectra/s]
  D_2023_0725_RJ_28_k562.mzML:  99%|█████████▉| 57894/58318 [00:23<00:00, 2854.35spectra/s]
  D_2023_0725_RJ_28_k562.mzML: 100%|█████████▉| 58264/58318 [00:23<00:00, 3106.02spectra/s]
  D_2023_0725_RJ_28_k562.mzML: 100%|██████████| 58318/58318 [00:23<00:00, 2496.07spectra/s]
  WARNING: Skipped 56750 spectra with invalid precursor info
  Traceback (most recent call last):
    File "/usr/local/bin/casanovo", line 8, in <module>
      sys.exit(main())
    File "/usr/local/lib/python3.10/site-packages/rich_click/rich_command.py", line 367, in __call__
      return super().__call__(*args, **kwargs)
    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
      return self.main(*args, **kwargs)
    File "/usr/local/lib/python3.10/site-packages/rich_click/rich_command.py", line 152, in main
      rv = self.invoke(ctx)
    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
      return __callback(*args, **kwargs)
    File "/usr/local/lib/python3.10/site-packages/casanovo/casanovo.py", line 143, in sequence
      runner.predict(peak_path, output)
    File "/usr/local/lib/python3.10/site-packages/casanovo/denovo/model_runner.py", line 160, in predict
      test_index = self._get_index(peak_path, False, "")
    File "/usr/local/lib/python3.10/site-packages/casanovo/denovo/model_runner.py", line 394, in _get_index
      return Index(index_fname, filenames, valid_charge=valid_charge)
    File "/usr/local/lib/python3.10/site-packages/depthcharge/data/hdf5.py", line 104, in __init__
      self.add_file(ms_file)
    File "/usr/local/lib/python3.10/site-packages/depthcharge/data/hdf5.py", line 192, in add_file
      parser.read()
    File "/usr/local/lib/python3.10/site-packages/depthcharge/data/parsers.py", line 98, in read
      self.mz_arrays = np.concatenate(self.mz_arrays).astype(np.float64)
  ValueError: need at least one array to concatenate
```

It looks to me like it's skipping all the ms2 scans in the file because of "invalid prescursor info" and produces an error when there is no data left to process.

I can't imagine why it would be skipping them. Comet DDA search works, and the file does contain MS1 data.

## Environment:
- OS: Ubuntu 24.04
- Casanovo Version: 4.2.1
- Hardware Used: Happens on both CPU and GPU

**Comment by melihyilmaz** [comment]
Hi Mike,

There are two reasons why Casanovo skips spectra is invalid (see https://github.com/Noble-Lab/casanovo/issues/326#issuecomment-2098905184) and without looking at the mzML file, I'm not entirely sure what's the case here. Can you post some sample spectra from the file here or the share the file itself?

**Comment by mriffle** [comment]
I should have definitely searched the issues before posting, sorry about that. 

That comment was quite helpful, it looks like there isn't charge information in the mzML file at all...
