### ISSUE TITLE
`RuntimeError: stack expects each tensor to be equal size...` error on branch `dev_latest_depthcharge`

### ISSUE THREAD

**Issue by Lilferrit** [Noble-Lab/casanovo#419]
After running the command 

```
casanovo train sample_preprocessed_spectra.mgf -p sample_preprocessed_spectra.mgf -d ../data -o segfault
``` 
with `sample_data` as the current working directory I got this error before training started:

```
(depthcharge_upgrade) C:\Users\gavin\OneDrive\Documents\casanovo\sample_data>casanovo train sample_preprocessed_spectra.mgf -p sample_preprocessed_spectra.mgf -d ../data -o segfault 
Seed set to 454
INFO: Casanovo version 4.2.2.dev133+g46e9606.d20241008
INFO: Early stopping disabled
INFO: Training a model from:
INFO:   sample_preprocessed_spectra.mgf
INFO: Using the following validation files:
INFO:   sample_preprocessed_spectra.mgf
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
sample_preprocessed_spectra.mgf: 128 spectra [00:00, 2037.48 spectra/s]
sample_preprocessed_spectra.mgf: 128 spectra [00:00, 2006.45 spectra/s]
WARNING: D:\anaconda3\envs\depthcharge_upgrade\lib\site-packages\lightning\pytorch\callbacks\model_checkpoint.py:654: Checkpoint directory C:\Users\gavin\OneDrive\Documents\casanovo\data exists and is not empty.

WARNING: D:\anaconda3\envs\depthcharge_upgrade\lib\site-packages\lightning\pytorch\callbacks\model_checkpoint.py:654: Checkpoint directory C:\Users\gavin\OneDrive\Documents\casanovo\data exists and is not empty.

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name       | Type             | Params | Mode
--------------------------------------------------------
0 | encoder    | SpectrumEncoder  | 19.4 M | train
1 | decoder    | PeptideDecoder   | 28.4 M | train
2 | softmax    | Softmax          | 0      | train
3 | celoss     | CrossEntropyLoss | 0      | train
4 | val_celoss | CrossEntropyLoss | 0      | train
--------------------------------------------------------
47.9 M    Trainable params
0         Non-trainable params
47.9 M    Total params
191.498   Total estimated model params size (MB)
234       Modules in train mode
0         Modules in eval mode
Traceback (most recent call last):
  File "D:\anaconda3\envs\depthcharge_upgrade\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\anaconda3\envs\depthcharge_upgrade\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\anaconda3\envs\depthcharge_upgrade\Scripts\casanovo.exe\__main__.py", line 7, in <module>
  File "D:\anaconda3\envs\depthcharge_upgrade\lib\site-packages\rich_click\rich_command.py", line 367, in __call__
    return super().__call__(*args, **kwargs)
  File "D:\anaconda3\envs\depthcharge_upgrade\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "D:\anaconda3\envs\depthcharge_upgrade\lib\site-packages\rich_click\rich_command.py", line 152, in main
    rv = self.invoke(ctx)
  File "D:\anaconda3\envs\depthcharge_upgrade\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\anaconda3\envs\depthcharge_upgrade\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\anaconda3\envs\depthcharge_upgrade\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\gavin\OneDrive\Documents\casanovo\casanovo\casanovo.py", line 322, in train
    runner.train(train_peak_path, validation_peak_path)
  File "C:\Users\gavin\OneDrive\Documents\casanovo\casanovo\denovo\model_runner.py", line 215, in train
    self.trainer.fit(
  File "D:\anaconda3\envs\depthcharge_upgrade\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 538, in fit
    call._call_and_handle_interrupt(
  File "D:\anaconda3\envs\depthcharge_upgrade\lib\site-packages\lightning\pytorch\trainer\call.py", line 47, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "D:\anaconda3\envs\depthcharge_upgrade\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 574, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "D:\anaconda3\envs\depthcharge_upgrade\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 981, in _run
    results = self._run_stage()
  File "D:\anaconda3\envs\depthcharge_upgrade\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 1025, in _run_stage
    self.fit_loop.run()
  File "D:\anaconda3\envs\depthcharge_upgrade\lib\site-packages\lightning\pytorch\loops\fit_loop.py", line 197, in run
    self.setup_data()
  File "D:\anaconda3\envs\depthcharge_upgrade\lib\site-packages\lightning\pytorch\loops\fit_loop.py", line 263, in setup_data
    iter(self._data_fetcher)  # creates the iterator inside the fetcher
  File "D:\anaconda3\envs\depthcharge_upgrade\lib\site-packages\lightning\pytorch\loops\fetchers.py", line 111, in __iter__
    batch = super().__next__()
  File "D:\anaconda3\envs\depthcharge_upgrade\lib\site-packages\lightning\pytorch\loops\fetchers.py", line 60, in __next__
    batch = next(self.iterator)
  File "D:\anaconda3\envs\depthcharge_upgrade\lib\site-packages\lightning\pytorch\utilities\combined_loader.py", line 341, in __next__
    out = next(self._iterator)
  File "D:\anaconda3\envs\depthcharge_upgrade\lib\site-packages\lightning\pytorch\utilities\combined_loader.py", line 78, in __next__
    out[i] = next(self.iterators[i])
  File "D:\anaconda3\envs\depthcharge_upgrade\lib\site-packages\torch\utils\data\dataloader.py", line 630, in __next__
    data = self._next_data()
  File "D:\anaconda3\envs\depthcharge_upgrade\lib\site-packages\torch\utils\data\dataloader.py", line 673, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\anaconda3\envs\depthcharge_upgrade\lib\site-packages\torch\utils\data\_utils\fetch.py", line 43, in fetch
    return self.collate_fn(data)
  File "D:\anaconda3\envs\depthcharge_upgrade\lib\site-packages\torch\utils\data\_utils\collate.py", line 317, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "D:\anaconda3\envs\depthcharge_upgrade\lib\site-packages\torch\utils\data\_utils\collate.py", line 155, in collate
    clone.update({key: collate([d[key] for d in batch], collate_fn_map=collate_fn_map) for key in elem})
  File "D:\anaconda3\envs\depthcharge_upgrade\lib\site-packages\torch\utils\data\_utils\collate.py", line 155, in <dictcomp>
    clone.update({key: collate([d[key] for d in batch], collate_fn_map=collate_fn_map) for key in elem})
  File "D:\anaconda3\envs\depthcharge_upgrade\lib\site-packages\torch\utils\data\_utils\collate.py", line 142, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "D:\anaconda3\envs\depthcharge_upgrade\lib\site-packages\torch\utils\data\_utils\collate.py", line 214, in collate_tensor_fn
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [32, 111] at entry 0 and [32, 120] at entry 1
```

This output is from my local windows machine, but I got an equivalent error when running this same command on the cluster.

**Comment by Lilferrit** [comment]
It looks like this error is caused by peaks not being zero padded out to the same length across batches, for example in the sample data the shape of the m/z batch tensors are:

1. (32, 111)
2. (32,  120)
3. (32, 89)
4. (32, 110)

**Comment by Lilferrit** [comment]
I'm using this unit test as a test harness to debug this issue:

```python
def test_harness(tmp_path):
    data_path = TEST_DIR.parent / "sample_data" / "sample_preprocessed_spectra.mgf"
    run = functools.partial(
        CliRunner().invoke, casanovo.main, catch_exceptions=False
    )

    train_args = [
        "train",
        str(data_path),
        "--validation_peak_path",
        str(data_path),
        "--output_dir",
        str(tmp_path),
    ]

    run(train_args)
```

**Comment by Lilferrit** [comment]
As it turns out both the spectrum dataset and data loaders will retrieve the spectra in batches, so in the case that the batch size is set to 32, the spectrum dataset would yield 32 spectra per batch, but then the dataloader would retrieve 32 of those batches yielding 1024 total spectra. I fixed this by setting the spectrum dataloader batch size to `None`.
