### ISSUE TITLE
CPU mode does not work

### ISSUE THREAD

**Issue by wsnoble** [Noble-Lab/casanovo#43]
I'd like to run Casanovo on a machine with no GPU, just in "de novo" mode (i.e., without training the model).  The sample config.yaml file indicates that this is possible:

```
gpus: [0] #None for CPU, int list to specify GPUs
```

However, when I changed the above line to

```
gpus: None #None for CPU, int list to specify GPUs
```

I still get an error message:

```
 File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo_env/lib/python3.7/site-packages/pytorch_lightning/utilities/device_parser.py", line 131, in _normalize_parse_gpu_string_input
    return int(s.strip())
ValueError: invalid literal for int() with base 10: 'None'
```

The full output is listed below.  

```
casanovo --mode=denovo --model_path=../../../data/22-07-02_weights/pretrained_excl_mouse.ckpt --test_data_path=mgf --config_path=config.yaml
/net/noble/vol1/home/noble/miniconda3/envs/casanovo_env/lib/python3.7/site-packages/torch/cuda/__init__.py:83: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 9010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  ../c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
INFO: De novo sequencing with Casanovo...
INFO: Created a temporary directory at /tmp/tmp5l3bzhid
INFO: Writing /tmp/tmp5l3bzhid/_remote_module_non_scriptable.py
INFO: Reading 1 files...
mgf/2022_01_13_HAB_timeseries_DDA_54_17-17.mgf: 53109spectra [00:47, 1122.26spectra/s]
Traceback (most recent call last):
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo_env/bin/casanovo", line 8, in <module>
    sys.exit(main())
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo_env/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo_env/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo_env/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo_env/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo_env/lib/python3.7/site-packages/casanovo/casanovo.py", line 83, in main
    denovo(test_data_path, model_path, config, output_path)  
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo_env/lib/python3.7/site-packages/casanovo/denovo/train_test.py", line 242, in denovo
    num_sanity_val_steps=config['num_sanity_val_steps']
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo_env/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/env_vars_connector.py", line 38, in insert_env_defaults
    return fn(self, **kwargs)
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo_env/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 426, in __init__
    gpu_ids, tpu_cores = self._parse_devices(gpus, auto_select_gpus, tpu_cores)
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo_env/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1543, in _parse_devices
    gpu_ids = device_parser.parse_gpu_ids(gpus)
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo_env/lib/python3.7/site-packages/pytorch_lightning/utilities/device_parser.py", line 78, in parse_gpu_ids
    gpus = _normalize_parse_gpu_string_input(gpus)
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo_env/lib/python3.7/site-packages/pytorch_lightning/utilities/device_parser.py", line 131, in _normalize_parse_gpu_string_input
    return int(s.strip())
ValueError: invalid literal for int() with base 10: 'None'
```

**Comment by bittremieux** [comment]
Fixed in bd37733.
