### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'batch_first'

### ISSUE THREAD

**Issue by piaopu0120** [Noble-Lab/casanovo#9]
Hi,
I have tried two ways to run this project but both failed.
**Method 1**: `casanovo --mode=eval --model_path='./casanovo_pretrained_model_weights/' --test_data_path='./Casanovo_preprocessed_data/' --config_path='../casanovo/config.py' 
`
I got 
```
INFO: Evaluating Casanovo...
Traceback (most recent call last):
  File "/usr/local/bin/casanovo", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/casanovo/casanovo.py", line 37, in main
    test_evaluate(test_data_path, model_path, config_path)
  File "/usr/local/lib/python3.8/dist-packages/casanovo/denovo/train_test.py", line 146, in test_evaluate
    model_trained = Spec2Pep().load_from_checkpoint(
  File "/usr/local/lib/python3.8/dist-packages/casanovo/denovo/model.py", line 103, in __init__
    self.encoder = SpectrumEncoder(
  File "/usr/local/lib/python3.8/dist-packages/depthcharge/components/transformers.py", line 60, in __init__
    layer = torch.nn.TransformerEncoderLayer(
TypeError: __init__() got an unexpected keyword argument 'batch_first'
```

**Method 2**: `python casanovo.py --mode=eval --model_path='../../data/casanovo_pretrained_model_weights/' --test_data_path='../../data/Casanovo_preprocessed_data/' --config_path='config.py' 
`
I got:
```
Traceback (most recent call last):
  File "casanovo.py", line 3, in <module>
    from casanovo.denovo import train, test_evaluate, test_denovo
  File "/home/bio/casanovo-main/casanovo/casanovo.py", line 3, in <module>
    from casanovo.denovo import train, test_evaluate, test_denovo
ModuleNotFoundError: No module named 'casanovo.denovo'; 'casanovo' is not a package
```

**Comment by wsnoble** [comment]
Melih, can you add to the code a line to check whether the given argument is a file or a directory and to issue an error statement in the latter case?

**Comment by piaopu0120** [comment]
Hi, I tried the new command, but still got this wrong.
`casanovo --mode=eval --model_path='./model/pretrained_excl_human.ckpt' --test_data_path='./data/' --config_path='../../casanovo/config.py'`

====
```
INFO: Evaluating Casanovo...
Traceback (most recent call last):
  File "/usr/local/bin/casanovo", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/casanovo/casanovo.py", line 37, in main
    test_evaluate(test_data_path, model_path, config_path)
  File "/usr/local/lib/python3.8/dist-packages/casanovo/denovo/train_test.py", line 146, in test_evaluate
    model_trained = Spec2Pep().load_from_checkpoint(
  File "/usr/local/lib/python3.8/dist-packages/casanovo/denovo/model.py", line 103, in __init__
    self.encoder = SpectrumEncoder(
  File "/usr/local/lib/python3.8/dist-packages/depthcharge/components/transformers.py", line 60, in __init__
    layer = torch.nn.TransformerEncoderLayer(
TypeError: __init__() got an unexpected keyword argument 'batch_first'
```

**Comment by wfondrie** [comment]
Can you run the following and post the output?

```
pip show torch
```

**Comment by piaopu0120** [comment]
> 

Name: torch
Version: 1.8.0+cu111
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /usr/local/lib/python3.8/dist-packages
Requires: numpy, typing-extensions
Required-by: casanovo, depthcharge-ms, efficientnet-pytorch, pretrainedmodels, pytorch-lightning, timm, torchaudio, torchmetrics, torchvision

**Comment by wfondrie** [comment]
Thanks @piaopu0120. You'll need to upgrade to PyTorch >= 1.9 to use Casanovo. Version 1.9 is when they added the `batch_first` parameter. If you installed PyTorch with pip, you can do this with:

```
pip install --upgrade torch
```

@melihyilmaz - can you update `setup.cfg` to specify 1.9 as the minimum version?

**Comment by melihyilmaz** [comment]
torch>=1.9 added to `setup.cfg`, closing this issue.
